from pathlib import Path
p=Path('app/skills/ingestion/references/validation-policy.md')
s=p.read_text(encoding='utf-8')
s=s.replace('''A missing ontology-required `Published` status is a readiness issue when the\nsource never states it. Adding `Published` without supporting source is instead\nan extraction grounding error (`PROPERTY_VALUE_NOT_GROUNDED`).\n''','''Lifecycle/status attributes marked `ingestionPolicy.mode=runtime_managed` are not required from source documents. The compiler supplies the configured safe runtime value (for example `Draft`). If a source-emitted literal is unsupported, it is still an extraction grounding error; do not fabricate `Published`.\n''',1)
s=s.replace('''Validation stores a fingerprint only when both flags are true. The fingerprint\nbinds the compiled patch, evidence and coverage, raw artifact digest, exact\nontology bytes, and compiler schema version. It exists only for the current\ninvocation.\n\nFill recompiles the current draft, compares the fingerprint, defensively\nreassesses it against the same prepared source chunks, then writes all nodes and\nedges in one Neo4j transaction. Missing/mismatched state returns\n`VALIDATION_PRECONDITION`.\n''','''Strict validation stores a persistence gate fingerprint when both flags are true. The fingerprint binds the compiled patch, evidence and coverage, raw artifact digest, exact ontology bytes, and compiler schema version.\n\nFor an explicit user-requested debug/partial commit, `allow_partial_persistence=true` may bypass readiness only after `validForExtraction=true`. The finalized patch is fingerprinted and reassessed against the same source chunks before write. Extraction, grounding, schema, domain/range, dangling-reference, and semantic errors remain blocking. Partial commits return `partialPersistence=true`, `persistenceMode=partial`, and the ignored readiness issues.\n\nFill writes the compiled nodes/edges in one Neo4j transaction and verifies readback. Missing/mismatched state returns `VALIDATION_PRECONDITION`.\n''',1)
p.write_text(s,encoding='utf-8')

p=Path('app/skills/ingestion/references/examples.md')
s=p.read_text(encoding='utf-8')
s=s.replace('''Because the cited source does not state `Published`, validation returns `PROPERTY_VALUE_NOT_GROUNDED`. Omit the status and allow persistence readiness to report the missing governance value.\n''','''Because the cited source does not state `Published`, do not emit it as a source fact. Omit the status; when the ontology marks that status as `runtime_managed`, the compiler supplies its configured safe value such as `Draft`.\n''',1)
s=s.replace('''After any change, submit the complete draft to validation again. Fill only after both validation flags are true in the same invocation.\n''','''After any change, submit the complete draft to validation again. Normal fill requires both validation flags. Only an explicit user request to inspect/debug an incomplete but extraction-valid graph may use `allow_partial_persistence=true`; extraction errors are never bypassed.\n''',1)
p.write_text(s,encoding='utf-8')
print('updated validation references')