from pathlib import Path
p=Path(r'D:\Thuc_tap_MB\google-adk-skill-practice\app\tools\ingestion_tools.py')
s=p.read_text(encoding='utf-8')
s=s.replace('    batch = workspace.batches[batch_index]\n    return {\n        "retryRequired": True,', '    return {\n        "retryRequired": True,')
start=s.index('def _repair_instructions(')
end=s.index('\ndef _compact_ontology_context', start)
new='''def _repair_instructions(summary: dict[str, Any]) -> str:\n    instructions: list[str] = []\n    codes = set(summary["codes"])\n    if "PROPERTY_VALUE_NOT_GROUNDED" in codes:\n        instructions.append("For unsupported property values, copy the exact source wording/value or omit the property; do not paraphrase business facts.")\n    if summary["evidenceTextNotInSourceLocations"]:\n        instructions.append("Use verbatim evidence text from the cited chunk.")\n    if "DERIVED_PROPERTY_REQUIRES_EDGE_EVIDENCE" in codes:\n        instructions.append("Add the grounded relationship edge that supports the derived ruleType, or omit the unsupported rule node.")\n    if summary["coverageNotEvidencedChunkIndexes"]:\n        instructions.append("For each coverageNotEvidenced chunk, add at least one grounded property/edge fact only when it contributes a distinct graph fact; otherwise mark it NOT_RELEVANT with a source-based reason.")\n    if summary["schemaErrorLocations"]:\n        instructions.append("Fix every schema error before resubmitting the same batch.")\n    return " ".join(instructions) or "Correct the batch validation errors and resubmit this same batch."\n\n\ndef _batch_validation_response(\n    workspace: IngestionWorkspace,\n    batch_index: int,\n    issues: list[ValidationIssue],\n    *,\n    schema_error_locations: list[str] | None = None,\n) -> dict[str, Any]:\n    summary = _batch_error_summary(issues, schema_error_locations=schema_error_locations)\n    retry = _batch_retry_payload(workspace, batch_index)\n    preview = issues[:10]\n    return {\n        "success": False,\n        "stage": "batch_validation",\n        "batchIndex": batch_index,\n        "retryRequired": retry["retryRequired"],\n        "nextAction": retry["nextAction"],\n        "errorCount": len(issues),\n        "errorsTruncated": len(issues) > len(preview),\n        "errors": [issue.model_dump(by_alias=True, exclude_none=True) for issue in preview],\n        "errorSummary": summary,\n        "repairInstructions": _repair_instructions(summary),\n        "affectedChunkIndexes": summary["coverageNotEvidencedChunkIndexes"],\n    }\n\n'''
s=s[:start]+new+s[end+1:]
p.write_text(s,encoding='utf-8')
print('retry response compacted')
