from pathlib import Path
p=Path('app/services/ingestion/fill_service.py')
s=p.read_text(encoding='utf-8')
s=s.replace('''        source_chunks: list[DocumentChunk] | list[dict[str, Any]] | None = None,\n    ) -> dict[str, Any]:\n''','''        source_chunks: list[DocumentChunk] | list[dict[str, Any]] | None = None,\n        *,\n        allow_partial_persistence: bool = False,\n    ) -> dict[str, Any]:\n''',1)
s=s.replace('''        if (\n            not assessment.result.valid_for_persistence\n            or assessment.compiled_patch is None\n        ):\n            raise FillValidationError(assessment.result)\n\n        patch = assessment.compiled_patch\n''','''        if assessment.compiled_patch is None or not assessment.result.valid_for_extraction:\n            raise FillValidationError(assessment.result)\n        partial_persistence = not assessment.result.valid_for_persistence\n        if partial_persistence and not allow_partial_persistence:\n            raise FillValidationError(assessment.result)\n\n        patch = assessment.compiled_patch\n''',1)
old='''        return FillResult(\n            status=(\n                FillStatus.SUCCESS\n                if receipt.verified\n                else FillStatus.READBACK_MISMATCH\n            ),\n            commitStatus=CommitStatus.COMMITTED,\n            nodes=len(patch.nodes),\n            edges=len(patch.edges),\n            nodeIds=write_result.node_ids,\n            relationshipIds=write_result.relationship_ids,\n            receipt=receipt,\n        ).model_dump(by_alias=True, mode="json")\n'''
new='''        result = FillResult(\n            status=(FillStatus.SUCCESS if receipt.verified else FillStatus.READBACK_MISMATCH),\n            commitStatus=CommitStatus.COMMITTED, nodes=len(patch.nodes), edges=len(patch.edges),\n            nodeIds=write_result.node_ids, relationshipIds=write_result.relationship_ids, receipt=receipt,\n        ).model_dump(by_alias=True, mode="json")\n        result["partialPersistence"] = partial_persistence\n        result["persistenceMode"] = "partial" if partial_persistence else "strict"\n        result["readinessIssuesIgnored"] = [issue.model_dump(by_alias=True, exclude_none=True) for issue in assessment.result.readiness_issues] if partial_persistence else []\n        return result\n'''
assert old in s
p.write_text(s.replace(old,new,1),encoding='utf-8')
print('patched FillService partial persistence')